module.exports = {
      content: ["./index.html", "./src/**/*.{js,jsx}"],
 darkMode: "class",
      theme: {
        extend: {
          colors: {
            "outline-variant": "#c1c8c2",
            "on-secondary-fixed-variant": "#394c33",
            "on-tertiary-container": "#bd9852",
            "on-tertiary-fixed": "#261900",
            "secondary-fixed-dim": "#b7cdad",
            "secondary-container": "#d0e6c5",
            "surface-container-highest": "#e5e2dc",
            "on-secondary": "#ffffff",
            "primary-container": "#1b3b2b",
            "secondary-fixed": "#d3e9c8",
            "on-tertiary": "#ffffff",
            "on-background": "#1c1c18",
            "on-error-container": "#93000a",
            "tertiary-fixed": "#ffdea5",
            "on-error": "#ffffff",
            "on-primary-fixed": "#002113",
            "surface-variant": "#e5e2dc",
            "error-container": "#ffdad6",
            "on-surface-variant": "#424843",
            "secondary": "#506449",
            "inverse-surface": "#31312d",
            "primary-fixed": "#c7ebd4",
            "on-primary-fixed-variant": "#2d4d3c",
            "tertiary-fixed-dim": "#e9c176",
            "surface": "#fcf9f3",
            "primary-fixed-dim": "#abcfb8",
            "primary": "#032517",
            "outline": "#727973",
            "inverse-primary": "#abcfb8",
            "on-tertiary-fixed-variant": "#5d4201",
            "surface-tint": "#456553",
            "on-secondary-fixed": "#0e200b",
            "surface-bright": "#fcf9f3",
            "background": "#fcf9f3",
            "surface-container-lowest": "#ffffff",
            "surface-dim": "#dcdad4",
            "error": "#ba1a1a",
            "on-primary-container": "#83a590",
            "surface-container-high": "#ebe8e2",
            "inverse-on-surface": "#f3f0ea",
            "tertiary-container": "#473100",
            "on-secondary-container": "#54684d",
            "on-primary": "#ffffff",
            "on-surface": "#1c1c18",
            "surface-container": "#f0eee8",
            "surface-container-low": "#f6f3ed",
            "tertiary": "#2c1d00"
          },
          borderRadius: {
            "DEFAULT": "0.125rem",
            "lg": "0.25rem",
            "xl": "0.5rem",
            "full": "0.75rem",
            "sm": "0.125rem"
          },
          spacing: {
            "gutter": "1.5rem",
            "margin": "2rem",
            "space-sm": "0.5rem",
            "space-xs": "0.25rem",
            "space-xl": "3.5rem",
            "space-lg": "2rem",
            "space-md": "1rem"
          },
          fontFamily: {
            "headline-sm": ["Playfair Display", "serif"],
            "headline-md": ["Playfair Display", "serif"],
            "headline-xl": ["Playfair Display", "serif"],
            "display-lg": ["Playfair Display", "serif"],
            "body-md": ["EB Garamond", "serif"],
            "label-md": ["Playfair Display", "serif"],
            "label-lg": ["Playfair Display", "serif"],
            "body-lg": ["EB Garamond", "serif"],
            "headline-xl-mobile": ["Playfair Display", "serif"],
            "label-sm": ["Playfair Display", "serif"],
            "display-lg-mobile": ["Playfair Display", "serif"],
            "headline-lg": ["Playfair Display", "serif"],
            "body-sm": ["EB Garamond", "serif"]
          },
          fontSize: {
            "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "0.02em", fontWeight: "600" }],
            "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "0.02em", fontWeight: "500" }],
            "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "400" }],
            "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.01em", fontWeight: "400" }],
            "body-md": ["17px", { lineHeight: "26px", letterSpacing: "0.01em", fontWeight: "400" }],
            "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.15em", fontWeight: "600" }],
            "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.12em", fontWeight: "600" }],
            "body-lg": ["19px", { lineHeight: "30px", letterSpacing: "0.01em", fontWeight: "400" }],
            "headline-xl-mobile": ["30px", { lineHeight: "38px", letterSpacing: "0em", fontWeight: "400" }],
            "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.18em", fontWeight: "600" }],
            "display-lg-mobile": ["38px", { lineHeight: "46px", letterSpacing: "0em", fontWeight: "400" }],
            "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "0.01em", fontWeight: "500" }],
            "body-sm": ["15px", { lineHeight: "22px", letterSpacing: "0.015em", fontWeight: "400" }]
          }
        }
      }
    }